### ISSUE TITLE
Issues with Environmental Replication in Minikube/Kubernetes

### ISSUE THREAD

**Issue by number101010** [datawire/telepresence#210] opened 2017-07-02 14:03 UTC
I'm not sure if this is a bug or just a limitation in how telepresence works.  I'm trying to put together a vscode integration using telepresence to do kubernetes development:

https://github.com/number101010/go-kubernetes-vscode-dev

I'm using telepresence to run delve for remote debugging like so:

```
telepresence --method=inject-tcp \
                     --expose=2345 \
                     --run bash -c unset DYLD_INSERT_LIBRARIES && dlv debug --listen=0.0.0.0:2345 --headless=true --log=true &
```

Then vscode connects to the remote debugger which is "inside" the kubernetes cluster thanks to the magic of telepresence.  It works really nicely!

However, when I try to create a go Kubernetes client I am running into 2 roadblocks.  First, the following env vars are not set:

`KUBERNETES_SERVICE_PORT`
`KUBERNETES_SERVICE_HOST`

If I manually set those environment variables I can move past that issue.   But then I get this error:

`panic: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory`

**Questions**

- In my telepresence "session" should I be able to access the "in container" file system?   Should `/var/run/secrets/kubernetes.io/serviceaccount/token` be visible?  Any recommendations on accomplishing this?
- If I run `telepresence --method=inject-tcp --run-shell` I can access $KUBERNETES_SERVICE_HOST.  However, if I run `telepresence --method=inject-tcp --run bash -c "echo $KUBERNETES_SERVICE_HOST"` it prints nothing.  Seems like `bash -c` is inheriting the wrong environment?  Just an observation.  Not sure if you consider this a telepresence bug or if you can even do anything about it.

**Comment by number101010** [comment] 2017-07-02 16:38
Ok, I was able to fix my environmental issue.  For whatever reason `bash -c` was losing the telepresence environment and was instead using my local machine's.

I just put my two lines
```
unset DYLD_INSERT_LIBRARIES
dlv debug --listen=0.0.0.0:2345 --headless=true --log=true
```
in a script and ran that.

Still really interested in potential ways to access the container file system tho.

**Comment by itamarst** [comment] 2017-07-03 13:07
Hi,

Thanks for using Telepresence, and for the bug report.

If you're using Go programs the recommended method is `vpn-tcp`. In fact, as of the latest release it's the default everywhere, so you can also just omit `--method` altogether. Once you're using `vpn-tcp` Go programs should get transparent networking.

As far as volumes go, they are there, they're just not as transparent until we can figure out a workaround to some of OS X's limitations: `$TELEPRESENCE_ROOT` has the root directory where volumes are mounted. See http://www.telepresence.io/reference/proxying.html#volumes

Does that fix your problem?

**Comment by itamarst** [comment] 2017-07-03 13:16
I think to address the volumes problem I will try to make it clearer in documentation how it works, by having a top-level howto for volume access.

**Comment by itamarst** [comment] 2017-07-03 13:33
OK, volume support is now a top-level thing in the docs: http://www.telepresence.io/howto/volumes.html

**Comment by number101010** [comment] 2017-07-03 16:24
Excellent, thanks for the reply.  Apologies for not doing a good job reading the documentation on volumes.

Last night I noticed that, even though the debugger was connecting, it wasn't proxying http queries into the cluster as expected.  This feels so close to being really cool.  If we could only work out these wrinkles it's so much faster than my current build/debug pipeline.

Anyway, I tried your suggestion of "vpn-tcp".  Here's my command:

`telepresence --method=vpn-tcp --expose=2345 --run .debug/runDelve.sh`

Contents of runDelve.sh below.  The unset command is b/c dlv gets pissy when that env var is set.  I tried removing that line, but I got the same error regardless when using `vpn-tcp`.  

```
unset DYLD_INSERT_LIBRARIES

dlv debug --listen=0.0.0.0:2345 --headless=true --log=true
```

I'm consistently getting this error when running with `vpn-tcp`:

```
Looks like there's a bug in our code. Sorry about that!

Here's the traceback:

Traceback (most recent call last):
  File "/usr/local/bin/telepresence", line 131, in call_f
    return f(*args, **kwargs)
  File "/usr/local/bin/telepresence", line 1863, in go
    runner, remote_info, args, env, subprocesses, socks_port, ssh
  File "/usr/local/bin/telepresence", line 1611, in run_local_command
    p = Popen(command, env=env)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error


And here are the last few lines of the logfile (see ./telepresence.log for the complete logs):

2017-07-03T16:19:26+0000 [stdout#info] RESOLVING b'localhost.default.svc.cluster.local'
2017-07-03T16:19:26+0000 [DNSDatagramProtocol (UDP)] DNSDatagramProtocol starting on 12295
2017-07-03T16:19:26+0000 [DNSDatagramProtocol (UDP)] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fb627fecc50>
2017-07-03T16:19:26+0000 [stdout#info] A query: b'localhost'
2017-07-03T16:19:26+0000 [stdout#info] RESOLVING b'localhost.default.svc.cluster.local'
2017-07-03T16:19:26+0000 [DNSDatagramProtocol (UDP)] DNSDatagramProtocol starting on 24765
2017-07-03T16:19:26+0000 [DNSDatagramProtocol (UDP)] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fb627fec748>
2017-07-03T16:19:26+0000 [stdout#info] FAILED to lookup b'localhost.default.svc.cluster.local' ([Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DNSNameError'>: <Message id=42573 rCode=3 maxSize=0 flags=answer,recDes,recAv queries=[Query('localhost.default.svc.cluster.local', 1, 1)] authority=[<RR name=cluster.local type=SOA class=IN ttl=60s auth=False>]>
2017-07-03T16:19:26+0000 [stdout#info] ]), trying b'localhost'
2017-07-03T16:19:26+0000 [DNSDatagramProtocol (UDP)] DNSDatagramProtocol starting on 17916
2017-07-03T16:19:26+0000 [DNSDatagramProtocol (UDP)] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fb627fec128>
2017-07-03T16:19:26+0000 [stdout#info] FAILED to lookup b'localhost.default.svc.cluster.local' ([Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DNSNameError'>: <Message id=10662 rCode=3 maxSize=0 flags=answer,recDes,recAv queries=[Query('localhost.default.svc.cluster.local', 1, 1)] authority=[<RR name=cluster.local type=SOA class=IN ttl=60s auth=False>]>
2017-07-03T16:19:26+0000 [stdout#info] ]), trying b'localhost'
2017-07-03T16:19:26+0000 [-] (UDP Port 12295 Closed)
2017-07-03T16:19:26+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fb627fecc50>
2017-07-03T16:19:26+0000 [-] (UDP Port 24765 Closed)
2017-07-03T16:19:26+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fb627fec748>
2017-07-03T16:19:26+0000 [-] (UDP Port 17916 Closed)
2017-07-03T16:19:26+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fb627fec128>
Running: (['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence')"],)... ran!
```

**Comment by itamarst** [comment] 2017-07-03 16:52
1. The `unset DYLD`_INSERT_LIBRARIES is not necessary with `--method vpn-tcp`.
2. The problem is probably due to runDelve.sh missing a `#!/bin/bash` line. So either add that, or just do `telepresence --run dlv debug --listen=0.0.0.0:2345 --headless=true --log=true`.

**Comment by number101010** [comment] 2017-07-03 21:34
New error.  Command line:

`telepresence --method=vpn-tcp --expose=2345 --run telepresence --run dlv debug --listen=0.0.0.0:2345 --headless=true --log=true`

Now I'm getting:

```
Here's the traceback:

Traceback (most recent call last):
  File "/usr/local/bin/telepresence", line 131, in call_f
    return f(*args, **kwargs)
  File "/usr/local/bin/telepresence", line 1863, in go
    runner, remote_info, args, env, subprocesses, socks_port, ssh
  File "/usr/local/bin/telepresence", line 1610, in run_local_command
    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
  File "/usr/local/bin/telepresence", line 1466, in connect_sshuttle
    get_hellotelepresence()
  File "/usr/local/bin/telepresence", line 1449, in get_hellotelepresence
    "import socket; socket.gethostbyname('hellotelepresence')"
  File "/usr/local/bin/telepresence", line 237, in get_output
    **kwargs).strip(), "utf-8"
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence')"]' returned non-zero exit status 1.


And here are the last few lines of the logfile (see ./telepresence.log for the complete logs):

2017-07-03T21:32:53+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f1a7e4c9b70>
2017-07-03T21:32:53+0000 [-] (UDP Port 28263 Closed)
2017-07-03T21:32:53+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f1a7e4634e0>
2017-07-03T21:32:53+0000 [-] (UDP Port 47720 Closed)
2017-07-03T21:32:53+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f1a7e4c91d0>
2017-07-03T21:32:53+0000 [-] (UDP Port 12662 Closed)
2017-07-03T21:32:53+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f1a7e4c9828>
Running: (['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence')"],)...Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
Running: (['sudo', 'killall', '-HUP', 'mDNSResponder'],)...c : DNS request from ('192.168.1.230', 55790) to None: 58 bytes
c : DNS request from ('192.168.1.230', 51682) to None: 59 bytes
c : DNS request from ('192.168.1.230', 54007) to None: 59 bytes
c : DNS request from ('192.168.1.230', 58402) to None: 57 bytes
c : DNS request from ('192.168.1.230', 53699) to None: 58 bytes
c : DNS request from ('192.168.1.230', 51758) to None: 58 bytes
 ran!
c : DNS request from ('192.168.1.230', 51113) to None: 58 bytes
c : DNS request from ('192.168.1.230', 57432) to None: 59 bytes
c : DNS request from ('192.168.1.230', 54641) to None: 59 bytes
```

**Comment by itamarst** [comment] 2017-07-04 11:29
Sorry you're having all these issues :( I am not working today due to holiday, but will see what I can do tomorrow.

Could you attach the telepresence.log file from the directory where you ran the command?

**Comment by number101010** [comment] 2017-07-04 12:43
No problem.  I appreciate the help.  Please ignore all of this on your day off :).

Good news. I found that this bug only occurs when when the OSX native vpn client is open.  So perhaps detecting that scenario and printing a nice error message is all that needs to occur.

[telepresence.log.txt](https://github.com/datawire/telepresence/files/1122046/telepresence.log.txt)

**Comment by number101010** [comment] 2017-07-04 18:45
Ran into a DNS issue.  Going to make a new thread since this one seems resolved.  Thanks for the help!

**Comment by itamarst** [comment] 2017-07-05 13:46
OK, I'll close this issue then and continue discussion there.

**Closed by itamarst** 2017-07-05 13:46 UTC
